import MySessionProvider from './MySessionProvider'
import TopNavBar from './TopNavBar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MySessionProvider>
        <TopNavBar />
        {children}
        </MySessionProvider>
      </body>
    </html>
  )
}
